# NixOS configuration for the `workd-dev` OrbStack machine (Milestone 2
# remote dogfood). Base settings vendored from the configuration.nix that
# OrbStack 2.2.1 generated at machine creation (2026-07-04); workd + Caddy
# additions are marked below. See README.md for the full runbook.
{
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    # Default lxd/incus container configuration (OrbStack machines are
    # lxc-style containers, not full VMs).
    "${modulesPath}/virtualisation/lxc-container.nix"
    # OrbStack-specific configuration, vendored from the generated file.
    ./orbstack.nix
  ];

  users = {
    # This being `true` leads to a few nasty bugs, change at your own risk!
    mutableUsers = false;

    users.chris = {
      uid = 501;
      extraGroups = ["wheel" "orbstack" "audio"];

      # simulate isNormalUser, but with an arbitrary UID (OrbStack matches
      # the macOS user's UID for the /Users file share)
      isSystemUser = true;
      group = "users";
      createHome = true;
      home = "/home/chris";
      homeMode = "700";
      useDefaultShell = true;
    };
  };

  time.timeZone = "America/Los_Angeles";

  networking = {
    # OrbStack generates the hostname into a separate autogenerated
    # incus.nix; owned here instead so the flake fully describes the machine.
    hostName = "workd-dev";

    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;

    # Caddy vhost below terminates TLS for workd.
    firewall.allowedTCPPorts = [80 443];
  };

  security = {
    sudo.wheelNeedsPassword = false;

    # Extra certificates from OrbStack (the host's OrbStack development root
    # CA, used for orb.local HTTPS services; public certificate, safe to
    # vendor).
    pki.certificates = [
      ''
        -----BEGIN CERTIFICATE-----
        MIICDDCCAbKgAwIBAgIQKRbUsy4BYyWEqrFtuNtFaDAKBggqhkjOPQQDAjBmMR0w
        GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
        cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
        IENBMB4XDTI2MDMwNTIwMDI0NloXDTM2MDMwNTIwMDI0NlowZjEdMBsGA1UEChMU
        T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
        aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
        ByqGSM49AgEGCCqGSM49AwEHA0IABEw8L7DzDU3QHaYI6Tsj5FSewV81QA4YZDDR
        /6Po5Ot3vtb7Cod/gxS3FMrPJ1Oun5QWCshyLp+6ov/x5sBukN+jQjBAMA4GA1Ud
        DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQoe++gSljWsWAO
        ITsa0CfyAmNsDzAKBggqhkjOPQQDAgNIADBFAiBoyP2JCVNthieu+9kGmUHdltNo
        QtEhSbwxTcl69oBlSQIhAI7Oixa2GwQYFl30LkeIg826RY0p734O5mt8r/Zw4W9e
        -----END CERTIFICATE-----
      ''
    ];
  };

  # Flakes for `nixos-rebuild switch --flake` runs inside the VM.
  nix.settings.experimental-features = ["nix-command" "flakes"];

  # --- workd + TLS (the dogfood additions) ---------------------------------

  services = {
    workd = {
      enable = true;
      # Loopback bind; Caddy terminates TLS in front (the documented
      # reverse-proxy stance).
      bind = "127.0.0.1:7878";
      # Dev token, provisioned manually (see README.md), never in the store.
      environmentFile = "/etc/workd/env";
      # Context preparation and the opencode harness need these on PATH.
      extraPackages = [
        pkgs.nix
        pkgs.opencode
      ];
    };

    # macOS trusts Caddy's internal-CA root cert once (see README.md);
    # workctl then talks plain https://workd-dev.orb.local with no
    # --insecure-http.
    caddy = {
      enable = true;
      virtualHosts."workd-dev.orb.local".extraConfig = ''
        tls internal
        reverse_proxy 127.0.0.1:7878
      '';
    };
  };

  systemd = {
    network = {
      enable = true;
      networks."50-eth0" = {
        matchConfig.Name = "eth0";
        networkConfig = {
          DHCP = "ipv4";
          IPv6AcceptRA = true;
        };
        linkConfig.RequiredForOnline = "routable";
      };
    };

    # Dogfood-side environment for the harness: DynamicUser gives the
    # service no usable HOME, and opencode locates auth.json via XDG.
    # Pointing XDG at the state directory is a deliberate workaround;
    # whether these belong in the workd module as options is a Milestone 2
    # finding.
    services.workd.environment = {
      HOME = "/var/lib/workd";
      XDG_DATA_HOME = "/var/lib/workd/xdg/data";
      XDG_CONFIG_HOME = "/var/lib/workd/xdg/config";
      XDG_CACHE_HOME = "/var/lib/workd/xdg/cache";
    };
  };

  # For more information, see `man configuration.nix` or
  # https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "25.11"; # Did you read the comment?
}
